name: Deploy Application
on:
  push:
    branches: [master]
  repository_dispatch:
    types: [backend-updated, frontend-updated]
  workflow_dispatch:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      backend-changed: ${{ steps.changes.outputs.backend }}
      frontend-changed: ${{ steps.changes.outputs.frontend }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 2

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            backend:
              - 'socialnetwork_api/**'
            frontend:
              - 'SW/**'

  deploy-backend:
    needs: detect-changes
    if: needs.detect-changes.outputs.backend-changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Clone backend
        run: git clone https://github.com/Black1955/socialnetwork_api.git

      - name: build docker
        run: docker build -t "${{secrets.DOCKER_USERNAME}}"/socialnetwork_api:latest ./socialnetwork_api

      - name: login to dockerhub
        run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin

      - name: push to dockerhub
        run: docker push "${{secrets.DOCKER_USERNAME}}"/socialnetwork_api:latest

  deploy-frontend:
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend-changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Clone backend
        run: git clone https://github.com/Black1955/socialnetwork_api.git

      - name: build docker
        run: docker build -t "${{secrets.DOCKER_USERNAME}}"/socialnetwork_frontend:latest .

      - name: login to dockerhub
        run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin

      - name: push to dockerhub
        run: docker push "${{secrets.DOCKER_USERNAME}}"/socialnetwork_frontend:latest
